services:
  bloom-app:
    build:
      context: ../../
      dockerfile: packages/docker-hub/Dockerfile.bloom-app
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_WS_BASE_URL=${VITE_WS_BASE_URL}
        - VITE_APP_NAME=${VITE_APP_NAME}
    env_file: .env
    ports:
      - "3000:80"
    volumes:
      - ../../packages/bloom-ui/src:/app/packages/bloom-ui/src
      - ../../packages/bloom-app/src:/app/packages/bloom-app/src
    restart: unless-stopped
